# Generated by Django 6.0.1 on 2026-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_profile_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Zaraz wracam'), ('busy', 'Zajęty'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
